stages: 
    - build
    - test
    - deploy

build-my-first-internship-job:
    stage: build
    script:
        - echo "this is first build job."

test-my-first-internship-job:
    stage: test
    script:
        - echo "this is first test job."

deploy-first-internship-job:
    stage: deploy
    script:
        - echo "this is deploy first job."
